#include "msocket.h"

int main()
{
    int id1 = m_socket(AF_INET, SOCK_MTP, 0);
    printf("%d\n", id1);
    // printTable();

    m_bind(id1, "127.0.0.1", 7511, "127.0.0.1", 4876);

    char buff[KB];
    char buff2[KB];

    struct sockaddr_in dest;
    dest.sin_addr.s_addr = inet_addr("127.0.0.1");
    dest.sin_port = htons(4876);
    dest.sin_family = AF_INET;
    int len = sizeof(dest);
    int sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);sleep(2);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);
    sb = m_recvfrom(id1, buff, KB, 0, (struct sockaddr *)&dest, &len);
    printf("Received message: %d --- %s\n", sb, buff);

    // while(1);
}